---
- name: Install nginx
  package: name=nginx state=latest

- name: Nginx config
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: Nginx default config
  template:
    src=default.conf.j2
    dest=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: Start/enable nginx service
  service: name=nginx enabled=yes state=started  
