---
- name: Install nginx
  package:
    name: nginx
  notify: reload nginx

- name: Install nginx modules
  package:
    name: "nginx-mod-{{ nginx_module_name }}"
  with_items: "{{ nginx_modules }}"
  loop_control:
    loop_var: nginx_module_name
