---
- name: Install nginx
  package:
    name: nginx
    state: latest

- name: Install nginx modules
  package:
    name: "nginx-mod-{{ nginx_module_name }}"
  with_items: "{{ nginx_modules }}"
  loop_control:
    loop_var: nginx_module_name

- name: Start/enable nginx service
  service:
    name: nginx
    enabled: yes
    state: started  
