---
- name: Install nginx
  package:
    name: nginx
    state: latest

- name: Install nginx modules
  package:
    name: "nginx-mod-{{ item }}"
  with_items: "{{ nginx_modules }}"

- name: Start/enable nginx service
  service:
    name: nginx
    enabled: yes
    state: started  
