---
- name: test nginx configuration
  command: nginx -t
  listen: reload nginx

- name: start nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started
  listen: reload nginx

- name: reload nginx service
  systemd:
    name: nginx
    state: reloaded
  listen: reload nginx
